controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mecanum_controller:
      type: clearpath_mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_controller:
  ros__parameters:
    use_stamped_vel: false
    reference_timeout: 0.0
    command_timeout: 1.0
    command_joint_names:
      - wheel_front_right_joint
      - wheel_front_left_joint
      - wheel_rear_right_joint
      - wheel_rear_left_joint
    interface_name: velocity
    kinematics:
      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0
      wheels_radius: 0.1
      sum_of_robot_center_projection_on_X_Y_axis: 1.590 # 0.870 + 0.720
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]